### ISSUE TITLE
After playing Control the Weak, the bot balked at the house choice phase 

### ISSUE THREAD

**Issue by blinkingline** [saluk/keyteki#4]
I forgot to grab a Screenshot.  Was playing Sonshen, the "Marchioness" of Bullies against the bot. I had just played a big Dis turn, finishing with Control the Weak and choosing Shadows (which the bot had just played).  After finishing my turn the Bot sat, but never defined it's hand or called Shadows.

**Comment by saluk** [comment]
Looks like the bot *really* wants to pick the house based on cards+board, no matter what the rules say: "Error: Couldn't click on "saurian" for bot."

**Comment by saluk** [comment]
closed
